server:
  port: 7769

spring:
  main:
    web-application-type: reactive

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: esta_es_mi_compleja_clave_secreta

  cloud:
    gateway:
      routes:

        - id: manufacturer
          uri: http://manufacturer-service:7770
          predicates:
            - Path=/manufacturer/**

        - id: train
          uri: http://train-service:7771
          predicates:
            - Path=/train/**

        - id: typeengine
          uri: http://typeengine-service:7772
          predicates:
            - Path=/typeengine/**

        - id: station
          uri: http://localhost:7773
          predicates:
            - Path=/station/**
          filters:
            - StripPrefix=1

        - id: line
          uri: http://localhost:7774
          predicates:
            - Path=/line/**
          filters:
            - StripPrefix=1

        - id: maintenance
          uri: http://maintenance-service:7775
          predicates:
            - Path=/maintenance/**

        - id: ticket
          uri: http://ticket-service:7776
          predicates:
            - Path=/ticket/**

        - id: city
          uri: http://localhost:7777
          predicates:
            - Path=/city/**
          filters:
            - StripPrefix=1

        - id: driver
          uri: http://driver-service:7778
          predicates:
            - Path=/driver/**

        - id: client
          uri: http://localhost:7779
          predicates:
            - Path=/client/**
          filters:
            - StripPrefix=1

        - id: auth
          uri: http://localhost:7780
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: supervisor
          uri: http://localhost:7781
          predicates:
            - Path=/supervisor/**
          filters:
            - StripPrefix=1

        - id: review
          uri: http://review-service:7782
          predicates:
            - Path=/review/**