spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.routes[0].id=engine-route
spring.cloud.gateway.routes[0].uri=http://localhost:7771
spring.cloud.gateway.routes[0].predicates[0]=Path=/engines-service/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/engines-service/(?<segment>.*), /api/engines/${segment}

spring.cloud.gateway.routes[1].id=train-route
spring.cloud.gateway.routes[1].uri=http://localhost:7770
spring.cloud.gateway.routes[1].predicates[0]=Path=/trains-service/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/trains-service/(?<segment>.*), /api/trains/${segment}

logging.level.org.springframework.cloud.gateway=DEBUG
management.endpoints.web.exposure.include=gateway